version: 2

project_name: paintress

before:
  hooks:
    - go mod tidy
    - go test ./... -count=1 -short

builds:
  - main: ./cmd/paintress/
    binary: paintress
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/hironow/paintress/internal/cmd.Version={{.Version}}
      - -X github.com/hironow/paintress/internal/cmd.Commit={{.ShortCommit}}
      - -X github.com/hironow/paintress/internal/cmd.Date={{.Date}}

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: checksums.txt
  algorithm: sha256

signs:
  - cmd: cosign
    args:
      - sign-blob
      - --yes
      - --output-signature=${signature}
      - ${artifact}
    artifacts: checksum

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

brews:
  - repository:
      owner: hironow
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/hironow/paintress"
    description: "Claude Code expedition orchestrator"
    license: "Apache-2.0"
    install: |
      bin.install "paintress"
    test: |
      system "#{bin}/paintress", "version"
