package domain

import (
	"time"

	"github.com/google/uuid"
)

// ImprovementTask represents a minimal task generated by the immediate layer
// when a corrective action is needed. It captures what to do, who should do it,
// and when the task expires.
type ImprovementTask struct {
	ID              string
	SourceEvent     string      // triggering event or D-Mail name
	TargetAgent     string      // which tool should act (sightjack/paintress/amadeus)
	SuggestedAction string      // what to do
	FailureType     FailureType // classification from the failure taxonomy
	Severity        Severity
	ExpiresAt       time.Time
	CreatedAt       time.Time
}

// NewImprovementTask creates a task with a unique ID and computed expiry.
func NewImprovementTask(sourceEvent, targetAgent, action string, ft FailureType, sev Severity, ttl time.Duration) ImprovementTask { // nosemgrep: domain-primitives.multiple-string-params-go -- sourceEvent/targetAgent/action are semantically distinct [permanent]
	now := time.Now().UTC()
	return ImprovementTask{
		ID:              uuid.New().String(),
		SourceEvent:     sourceEvent,
		TargetAgent:     targetAgent,
		SuggestedAction: action,
		FailureType:     ft,
		Severity:        sev,
		ExpiresAt:       now.Add(ttl),
		CreatedAt:       now,
	}
}

// Expired returns true if the task's validity window has passed (inclusive
// of the boundary instant). The check is `now >= ExpiresAt` so that
// constructing an ImprovementTask with TTL=0 (= ExpiresAt equals CreatedAt)
// is treated as "already expired" without depending on nanosecond-level
// scheduler timing. Using After alone caused a flaky failure in
// TestImprovementTask_Expired when the test's time.Now() coincided with
// the constructor's now.
func (t ImprovementTask) Expired() bool {
	return !time.Now().UTC().Before(t.ExpiresAt)
}
